name: ci

on:
  schedule:
    # build every tuesday
    - cron: '0 10 * * 2'
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4', '8.0' ]
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push ${{ matrix.php }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: pluswerk/php-pimcore:${{ matrix.php }}
          build-args: FROM=webdevops/php-nginx:${{ matrix.php }}
      -
        name: Build and push ${{ matrix.php }} dev
        id: docker_build_dev
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: pluswerk/php-pimcore:${{ matrix.php }}-dev
          build-args: FROM=pluswerk/php-dev:nginx-${{ matrix.php }}
      -
        name: Image digest
        run: |
          echo ${{ steps.docker_build.outputs.digest }}
          echo ${{ steps.docker_build_dev.outputs.digest }}
