name: CI

on: [pull_request]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: on pull request, Dockerfile lint 
      uses: jwr0/dockerfile-linter-action
