name: ci

on:
  schedule:
    # build every tuesday
    - cron: '0 10 * * 2'
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push 7.4
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: pluswerk/php-pimcore:latest
          build-args: FROM=webdevops/php-nginx:7.4
#      -
#        name: Build and push 7.4 dev
#        id: docker_build
#        uses: docker/build-push-action@v2
#        with:
#          push: true
#          tags: pluswerk/php-pimcore:latest
#          build-args: FROM=pluswerk/php-dev:nginx-7.4
#      -
#        name: Build and push 8.0
#        id: docker_build
#        uses: docker/build-push-action@v2
#        with:
#          push: true
#          tags: pluswerk/php-pimcore:latest
#          build-args: FROM=webdevops/php-nginx:8.0
#      -
#        name: Build and push 8.0 dev
#        id: docker_build
#        uses: docker/build-push-action@v2
#        with:
#          push: true
#          tags: pluswerk/php-pimcore:latest
#          build-args: FROM=pluswerk/php-dev:nginx-8.0
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
