name: ci

on:
  schedule:
    # build every first of the month
    - cron: '30 0 1 * *'
  push:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4', '8.0', '8.1', '8.2' ]
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push ${{ matrix.php }}
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/pluswerk/php-pimcore:${{ matrix.php }},ghcr.io/pluswerk/php-pimcore:${{ matrix.php }}-${{ steps.date.outputs.date }},pluswerk/php-pimcore:${{ matrix.php }},pluswerk/php-pimcore:${{ matrix.php }}-${{ steps.date.outputs.date }}
          build-args: FROM=webdevops/php-nginx:${{ matrix.php }}
      -
        name: Build and push ${{ matrix.php }} dev
        id: docker_build_dev
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/pluswerk/php-pimcore:${{ matrix.php }}-dev,ghcr.io/pluswerk/php-pimcore:${{ matrix.php }}-dev-${{ steps.date.outputs.date }},pluswerk/php-pimcore:${{ matrix.php }}-dev,pluswerk/php-pimcore:${{ matrix.php }}-dev-${{ steps.date.outputs.date }}
          build-args: FROM=ghcr.io/pluswerk/php-dev:nginx-${{ matrix.php }}
